version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  # PostgreSQL database service
  db:
    container_name: db
    hostname: db
    image: postgres:latest
    environment:
      POSTGRES_DB: db-insight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
